# My variables
name: PentestBox Blog
description: 
google_verification: null
baseurl: /blog
url: https://pentestbox.com



# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
